#!/usr/bin/env python3
"""Write data/live.json and data/events.json — resident-expat magazine layer."""
import json
from pathlib import Path

ROOT = Path("/workspace/data")


def p(text):
    return {"type": "p", "text": text}


def h2(text):
    return {"type": "h2", "text": text}


def ul(items):
    return {"type": "ul", "items": items}


def callout(text, tone="info", title=None):
    b = {"type": "callout", "tone": tone, "text": text}
    if title:
        b["title"] = title
    return b


def cta(label, href):
    return {"type": "cta", "label": label, "href": href}


stories = [
    {
        "slug": "hawker-without-looking-lost",
        "title": "How to walk into a hawker centre without looking lost",
        "kicker": "Food",
        "category": "food",
        "excerpt": "The first meal that makes you feel like you live here is not at a hotel buffet. It is chicken rice at a round table, tray in hand, uncle already taking the next order.",
        "updated": "14 September 2026",
        "readMinutes": 7,
        "featured": True,
        "hero": "/live/hawker.jpg",
        "tags": ["hawker", "food", "chicken rice", "maxwell", "old airport", "laksa"],
        "body": [
            p("If you only eat in Holland Village for the first six months, you will have lived in a very expensive version of home. The city happens at hawker centres. They are not rustic. They are the national canteen — air-conditioned now, in many cases, and still S$4–8 a plate."),
            h2("The move"),
            ul([
                "Walk the whole loop once before you queue. The good stall is rarely the first one you see from the door.",
                "Look at the trays coming off the counter, not the plastic photos. If those plates look like what you want, stand there.",
                "Have your order ready: “chicken rice, steamed, no cucumber, teh peng.” Singapore rewards speed, not speeches.",
                "Pay when the food comes unless they take it first. NETS/PayNow is normal in 2026; keep a S$10 note anyway.",
                "Share a round table. That is not a social invitation. Put your packet of tissues down to hold a seat, then go queue.",
            ]),
            h2("Five centres that teach you the island"),
            ul([
                "Maxwell (Chinatown) — tourist-heavy, still the fastest education in chicken rice, and the Tian Tian queue is a Singapore conversation starter.",
                "Old Airport Road — the east-side encyclopedia. Satay, oyster omelette, fried carrot cake. Go hungry.",
                "Tiong Bahru Market (upstairs) — breakfast with the neighbourhood. Downstairs is the wet market; that is the second lesson.",
                "Chomp Chomp (Serangoon Gardens) — night, open-air, the stall you will argue about with colleagues.",
                "Our Tampines Hub / a heartland mall food court — this is how most of the country actually eats on a Tuesday.",
            ]),
            callout("“Tissue packet on the table” is a reservation. Do not move someone else’s. Do not be precious about sitting with strangers.", "info", "The packet"),
            h2("What to order when you have no idea"),
            p("Chicken rice. Economic rice (cai png) if you want vegetables and three dishes pointed at with a pair of tongs. Minced meat noodles. Fish soup. Nasi lemak. If it is spicy, say “not too spicy” once — they will still make it Singapore-spicy."),
            p("Drink: kopi (coffee with condensed milk), kopi-o (black, sugar), kopi-c (evaporated milk), teh peng (iced tea). “Peng” means iced. You now speak a little of the language of the morning."),
            cta("Kopitiam vocabulary", "/live/kopitiam-vocabulary"),
        ],
    },
    {
        "slug": "weekend-that-isnt-orchard",
        "title": "A weekend that is not Orchard Road",
        "kicker": "Weekends",
        "category": "weekend",
        "excerpt": "The island is 50 km across. You can spend two years shopping the same three malls, or you can learn the coast, the reservoir, and the Causeway.",
        "updated": "12 September 2026",
        "readMinutes": 8,
        "featured": True,
        "hero": "/live/east-coast.jpg",
        "tags": ["weekend", "east coast", "macritchie", "cycling", "southern ridges", "parkrun"],
        "body": [
            p("Orchard is for when you need a phone fixed or a cinema with reserved seats. It is not a personality. The people who stay sane here have a Saturday loop that does not involve ION."),
            h2("Saturday morning"),
            ul([
                "Parkrun at East Coast or West Coast if you can bear 7.30am humidity. It is free, it is the same people every week, and that is how you make friends without “networking”.",
                "MacRitchie Reservoir — the Treetop Walk if you book, the boardwalk if you do not. Go before 8am or you will melt.",
                "East Coast Park: rent a bike at the McDonald’s end, ride toward Bedok, eat seafood at the chalets, swim if the flag is green.",
            ]),
            h2("Saturday afternoon, when it rains"),
            p("It will rain. Plan B is a museum with aircon (National Gallery is actually good; the Peranakan Museum is the one you should have gone to already) or a hawker centre you have not done. Do not default to a mall unless the children are melting."),
            h2("Sunday without leaving the island"),
            ul([
                "Southern Ridges: Henderson Waves at golden hour. You will share it with wedding photographers. Still worth it.",
                "Pulau Ubin if you want to remember that Singapore used to be kampung. First-come bicycles at the jetty. Last bumboat is real — check the time.",
                "Kampong Glam in the late afternoon, mosque first, then Haji Lane when the light goes pink, then dinner that is not a burger.",
            ]),
            callout("Car ownership here is a lifestyle choice, not a default. A weekend with EZ-Link/SimplyGo, a folding bike, and Grab for the last kilometre is how most new arrivals actually live.", "ok"),
            cta("Resident exits: JB, Bintan, Desaru", "/live/jb-bintan-desaru"),
        ],
    },
    {
        "slug": "belonging-in-90-days",
        "title": "How to belong in 90 days",
        "kicker": "Living here",
        "category": "social",
        "excerpt": "A pass is permission to work. Belonging is a kopi uncle who starts your order when you walk in, a clinic that has your file, and one person who would collect your mail.",
        "updated": "10 September 2026",
        "readMinutes": 9,
        "featured": True,
        "hero": "/live/kampong-glam.jpg",
        "tags": ["friends", "community", "settle", "social", "clubs", "belonging"],
        "body": [
            p("The lonely version of this city is a condo with a pool you never use and a Grab history of the same four restaurants. The other version is smaller, cheaper, and much more Singapore."),
            h2("Week 1–2: the boring infrastructure of a life"),
            ul([
                "Pick a GP within walking distance. Parkway, Raffles, or a neighbourhood clinic — you need a name, not a hospital A&E for a sore throat.",
                "Open the bank account, get PayNow, put your Singpass (if you have an EP/S Pass) to work. Cash is for the one stall that still wants it.",
                "Learn the bus that actually serves your block, not just the MRT. The last mile is where you live.",
            ]),
            h2("Week 3–6: one repeating thing"),
            p("Join one thing that meets every week. Not a Facebook group. A physical room. Hash House Harriers, a running club, a church, a mosque, a temple, CrossFit if you must, a language class at the community centre, Toastmasters, a football pitch booked on ActiveSG. The content of the hobby matters less than the fact that the same 20 people see you on Thursday."),
            h2("Week 7–12: get slightly local"),
            ul([
                "A hawker stall that knows you. That is not poetry. That is how lunch works.",
                "One Singaporean colleague you could text on a Sunday. You have to go first.",
                "A wet market Saturday. Even if you still buy yoghurt at Cold Storage.",
                "Learn two festival dates that are not Christmas. Show up to one.",
            ]),
            callout("Do not build your entire social life inside the nationality bubble. It is comfortable and it is how people leave after three years still unable to order in a kopitiam.", "warn", "The compound"),
            p("Belonging here is not becoming Singaporean. It is being a person the city can place. Address, clinic, stall, club, one friend who is not on your payroll. That is the whole trick."),
            cta("Sports clubs and repeating rooms", "/live/sports-clubs-repeating-rooms"),
        ],
    },
    {
        "slug": "kopitiam-vocabulary",
        "title": "Kopi, teh, and the rest of breakfast",
        "kicker": "Food",
        "category": "food",
        "excerpt": "Singapore breakfast is a dialect. Once you can order it, mornings get cheaper and better.",
        "updated": "8 September 2026",
        "readMinutes": 5,
        "hero": "/live/hawker.jpg",
        "tags": ["kopi", "teh", "kopitiam", "breakfast", "kaya"],
        "body": [
            p("A kopitiam is a coffee shop, often with a few cooked-food stalls around a drinks uncle who has been there longer than your visa category has existed."),
            h2("The drinks"),
            ul([
                "Kopi — coffee with condensed milk, the default.",
                "Kopi-o — black, sugar. Kopi-o kosong — black, no sugar.",
                "Kopi-c — evaporated milk, less sweet.",
                "Kopi peng — iced. Siu dai — less sugar. Gah dai — more, if you must.",
                "Teh follows the same grammar. Teh tarik is pulled milk tea.",
                "Yuan yang — coffee plus tea. It is not a joke.",
            ]),
            h2("The plate"),
            p("Kaya toast (coconut jam, cold butter, grilled bread) and two half-boiled eggs with white pepper and dark soy. That is the national breakfast. Add a plate of nasi lemak if you are actually hungry. It will still be under S$8."),
            callout("Pointing at the menu like a tourist is fine once. The second time, say the words. Uncles are not waiting to be your language teacher, but they are waiting for you to decide.", "info"),
        ],
    },
    {
        "slug": "public-holidays-2026",
        "title": "The 2026 holidays, and what they actually are",
        "kicker": "Culture",
        "category": "culture",
        "excerpt": "Singapore does not close for your home country’s calendar. It closes for other people’s holy days — and then the whole island goes somewhere.",
        "updated": "5 September 2026",
        "readMinutes": 6,
        "hero": "/live/kampong-glam.jpg",
        "tags": ["holidays", "cny", "hari raya", "deepavali", "national day", "vesak"],
        "body": [
            p("If you treat public holidays as “a day off”, you will spend them in a mall. If you treat them as other people’s festivals, the city opens."),
            h2("Still ahead in 2026"),
            ul([
                "Mid-Autumn Festival — Friday 25 September. Mooncakes in the office, lanterns at the Chinese Garden and in Chinatown. You will be offered a snow-skin. Accept it.",
                "Deepavali — 8 November. Little India is the point. Go in the evening. Eat. Do not complain about crowds you walked into.",
                "Christmas is a shopping season here, not a shutdown. 25 December is a holiday; 26th is often a working day. Plan flights accordingly.",
            ]),
            h2("Already passed, learn them for next year"),
            ul([
                "Chinese New Year — the two-day close, reunion dinners, ang bao etiquette if you have children of friends, and the week the CBD is empty.",
                "Hari Raya Puasa / Haji — visit if you are invited. Bring a box of cookies. Remove your shoes.",
                "Vesak — temples, and a quieter kind of crowd.",
                "National Day, 9 August — the parade if you balloted; the heartland fireworks if you did not. Wear red if you want to. Nobody will make you.",
            ]),
            callout("Do not book a moving truck, a helper’s rest-day swap, or a government appointment on the eve of CNY or a long weekend. Half the island is already on the Causeway.", "warn"),
            cta("Mid-Autumn without being awkward", "/live/mid-autumn-office"),
        ],
    },
    {
        "slug": "kids-after-school",
        "title": "After-school, without going broke",
        "kicker": "Family",
        "category": "family",
        "excerpt": "Enrichment is an arms race. Playgrounds, ActiveSG, libraries and the void deck are still how a lot of this country raises children.",
        "updated": "3 September 2026",
        "readMinutes": 7,
        "hero": "/live/playground.jpg",
        "tags": ["kids", "playground", "activesg", "library", "enrichment", "family"],
        "body": [
            p("International-school Saturdays can become a second mortgage of swimming, Mandarin, coding and “social tennis”. Some of that is useful. Most of it is other parents’ anxiety, priced in SGD."),
            h2("The free and almost-free layer"),
            ul([
                "NLS / NLB libraries — air-conditioned, board books, and the only place a toddler can be loud-ish at 4pm without a membership.",
                "Neighbourhood playgrounds and void decks. This is not slumming it. This is Singapore. The children you want your child to meet are already there.",
                "ActiveSG sports centres — public pools and courts. Book on the app. Non-citizens pay more; it is still not a country club.",
                "Gardens by the Bay outdoor gardens are free. The Cloud Forest is the paid bit, and you do not need it every weekend.",
            ]),
            h2("When you do pay"),
            p("Pick one thing the child actually likes. Swim is the one that matters in a country of condominium pools and sudden rain. Mandarin is the one that pays off if you stay. Everything else can wait until they ask."),
            callout("The “expat playground” circuit (Botanic Gardens playground, East Coast, Sentosa) is real and pleasant. Alternate with a heartland town square or you will raise a child who thinks Singapore is a park with a food court.", "info"),
        ],
    },
    {
        "slug": "paynow-nets-death-of-cash",
        "title": "PayNow, NETS, and the death of cash",
        "kicker": "Daily money",
        "category": "money",
        "excerpt": "By week two you should be able to split a hawker bill, pay a helper, and settle a Grab without opening a wallet.",
        "updated": "1 September 2026",
        "readMinutes": 6,
        "hero": "/live/marina-bay.jpg",
        "tags": ["paynow", "nets", "paylah", "banking", "cash"],
        "body": [
            p("Singapore in 2026 is allergic to notes. The stall that only takes cash still exists. It is not the majority, and you will feel it when you are the person holding up the queue counting coins."),
            h2("What to set up"),
            ul([
                "A local bank account (DBS/POSB, OCBC, UOB) linked to PayNow via NRIC or mobile. This is how people send you money.",
                "The bank’s app — DBS PayLah! if you went DBS. Scan QR. That is lunch.",
                "NETS on a debit card for the supermarket and the MRT/bus (SimplyGo).",
                "GrabPay or a credit card for rides. Do not use cash with a Grab driver unless you said so in the app.",
            ]),
            h2("The helper, the landlord, the school"),
            p("Maids are often paid via PayNow. Landlords still love a bank transfer on the 1st. Schools will give you a GIRO form and look at you until you fill it in. GIRO is the adult version of belonging."),
            callout("Keep S$20–50 cash for the one taxi with a broken machine, the temple donation, and the uncle who has not joined 2026. That is the whole cash strategy.", "ok"),
        ],
    },
    {
        "slug": "jb-bintan-desaru",
        "title": "Resident exits: JB, Bintan, Desaru",
        "kicker": "Weekends",
        "category": "weekend",
        "excerpt": "The island is small. Leaving it is a sport. Do it like someone who has to be at work on Monday.",
        "updated": "28 August 2026",
        "readMinutes": 7,
        "hero": "/live/east-coast.jpg",
        "tags": ["jb", "bintan", "desaru", "batam", "weekend", "causeway"],
        "body": [
            p("Leaving Singapore for 36 hours is how you stay. The mistake is treating it like a holiday to another country. It is a valve."),
            h2("Johor Bahru"),
            p("KTM into JB Sentral if you want to skip the Causeway car park. CIQ on a Saturday morning is a personality test. Go for seafood, dental work, a tailor, or a hotel with a pool that costs what a Tanglin lunch costs. Be back before Sunday night or you will join the famous queue."),
            h2("Bintan / Batam"),
            p("Ferries from HarbourFront. Bintan is resorts and beaches; Batam is more workaday. Passports, not ICs. Book the return ferry before you care about the hotel."),
            h2("Desaru"),
            p("A car or a bus, a coast, and a slower Malaysia. Worth it if you have children who need to run in a straight line."),
            callout("Long weekends: the Causeway is a parking lot. Either leave Thursday night or do not leave. Watch ICA and Waze like a hawk.", "warn", "Eve of holiday"),
        ],
    },
    {
        "slug": "dont-be-that-expat",
        "title": "Don’t be that expat",
        "kicker": "Culture",
        "category": "culture",
        "excerpt": "A short list of ways to live here without becoming the story Singaporeans tell about foreigners.",
        "updated": "26 August 2026",
        "readMinutes": 6,
        "hero": "/live/kampong-glam.jpg",
        "tags": ["etiquette", "culture", "race", "religion", "manners"],
        "body": [
            p("Singapore is polite until it is not. Most of the rules are not written. Breaking them does not get you deported. It just means people stop explaining things to you."),
            ul([
                "Do not skip the queue. There is always a queue. Join it.",
                "Take off your shoes in homes without being asked.",
                "Do not touch people’s heads. Do not point with your foot.",
                "Speak more quietly on the MRT than you think you need to. Phone speaker in a carriage is a moral failing.",
                "Chewing gum is not a personality. The ban is real enough.",
                "Do not compare everything to “back home” in the first twenty minutes of dinner.",
                "Race and religion are not ice-breakers. CMIO is how the state counts people; it is not your anecdote.",
                "Tip as the card machine suggests, or not at all in hawker centres. Do not perform American tipping in a chicken-rice stall.",
                "Your helper is a worker, not a character in your content.",
                "National Service is not a debate topic you were invited to.",
            ]),
            p("The positive version: learn names, eat the food, show up to the office lunch, say “sorry ah” when you bump someone, and mean it. That is 90% of looking like you live here."),
        ],
    },
    {
        "slug": "sports-clubs-repeating-rooms",
        "title": "Sports clubs and other repeating rooms",
        "kicker": "Social",
        "category": "social",
        "excerpt": "Friends in Singapore are a scheduling problem. Book a court, join a hash, or stand on a start line every Saturday.",
        "updated": "22 August 2026",
        "readMinutes": 6,
        "hero": "/live/east-coast.jpg",
        "tags": ["sports", "hash", "running", "activesg", "clubs", "friends"],
        "body": [
            p("People here work late and leave the country on Friday. If your social plan is “we should grab a drink sometime”, you will be alone. If your social plan is a booking, you will see the same faces."),
            h2("Where repeating happens"),
            ul([
                "Hash House Harriers — several hashes, several personalities, beer optional-not-really, jungle optional.",
                "Parkrun — East Coast, West Coast, Bedok, etc. 5 km, Saturday, free.",
                "ActiveSG — book badminton, tennis, football. Non-members of anything can still play.",
                "The traditional clubs (Tanglin, SCC, Dutch, American, British) — expensive, useful if your company pays, not required to have a life.",
                "Climbing gyms, CrossFit boxes, yoga that is not a personality cult. Six months of showing up beats a mixer.",
                "Volunteer: Habitat, animal shelters, migrant-worker groups. Singapore will take your time.",
            ]),
            callout("InterNations and the Facebook groups are how you find the first event. They are not a community. The second event is the one you should go to.", "info"),
        ],
    },
    {
        "slug": "f1-month-if-you-live-here",
        "title": "F1 month, if you live here",
        "kicker": "This season",
        "category": "city",
        "excerpt": "The Singapore Grand Prix is 9–11 October 2026 — first Sprint weekend, The Killers, Lana Del Rey. Also: road closures from 7 October. Plan like a resident, not a spectator.",
        "updated": "14 September 2026",
        "readMinutes": 6,
        "featured": True,
        "hero": "/live/marina-bay.jpg",
        "tags": ["f1", "formula 1", "marina bay", "october", "road closures", "lana del rey"],
        "body": [
            p("If you do not have a ticket, F1 is still your problem. LTA closes Marina Centre and Padang-area roads from 12.01am on 7 October through the morning of 13 October. The race itself is 9–11 October under the lights. Last trains from City Hall run late on event nights."),
            h2("If you are going"),
            ul([
                "This is Singapore’s first F1 Sprint weekend. Friday is not a quiet practice day.",
                "Concert stages are bundled with race tickets. The Killers Saturday, Lana Del Rey Sunday — treat that as the reason half your office is “working from home” adjacent to the bay.",
                "MRT. Not a car. Not a Grab that will be surging and stuck.",
            ]),
            h2("If you are not going"),
            p("Avoid the bay. Eat in the heartlands. Book nothing that assumes you can cross Marina Centre. Host the people who flew in, or leave for JB on Thursday 8 October before the island performs itself."),
            callout("Work from home those three days if you can. The CBD is a concert with a racetrack in it.", "warn"),
            cta("What’s on", "/events"),
        ],
    },
    {
        "slug": "wet-market-vs-cold-storage",
        "title": "Wet market vs Cold Storage",
        "kicker": "Food",
        "category": "food",
        "excerpt": "You can grocery-shop this island like a hotel guest, or you can learn the morning market and cut the bill in half.",
        "updated": "18 August 2026",
        "readMinutes": 5,
        "hero": "/live/hawker.jpg",
        "tags": ["wet market", "ntuc", "cold storage", "little farms", "groceries"],
        "body": [
            p("Cold Storage and Little Farms are where the country stores imported cheese. NTUC FairPrice is where the country actually shops. The wet market is where the fish still has eyes."),
            ul([
                "Wet market (often under a hawker centre): veg, tofu, fish, chicken, cut fruit. Morning. Bring bags. Point, then PayNow.",
                "NTUC — house brands, diapers, the weekly shop. Every town.",
                "Cold Storage / Market Place — when you need the thing from home. You will pay for the feeling.",
                "Mustafa (Little India) — 24 hours, everything, a little chaotic, occasionally the only place that has your home-brand chilli sauce.",
            ]),
            p("A reasonable split: wet market twice a week for produce, NTUC for bulk, Cold Storage as a treat. Your helper, if you have one, already knows this. Ask her. Pay her for the knowledge."),
        ],
    },
    {
        "slug": "haze-humidity-nea",
        "title": "Haze, humidity, and the NEA text",
        "kicker": "The city",
        "category": "city",
        "excerpt": "The weather here is a policy area. Learn the PSI the way you learned to check rain at home.",
        "updated": "15 August 2026",
        "readMinutes": 4,
        "hero": "/live/marina-bay.jpg",
        "tags": ["haze", "psi", "nea", "humidity", "weather"],
        "body": [
            p("It is hot. It will not stop being hot. The indoor world is 23°C and the outdoor world is a wet towel. You dress for the five minutes between them, which is why people carry a cardigan and still shine."),
            h2("Haze"),
            p("When Sumatra burns, Singapore gets a number. PSI. Under 100, live your life. 100–200, kids and the elderly stay in. Above that, the country talks about it on the news and you cancel the East Coast ride. NEA will tell you. So will every group chat."),
            h2("Rain"),
            p("Flash floods happen on the same five roads every year. If you live in a low-lying pocket (some of Katong, some of the west), you will learn which. Do not drive into a underpass because the car in front did."),
            callout("Aircon is not a luxury; it is how paint survives. Budget the bill. A 3-bed on full blast in May is a different number from July in Europe.", "info"),
        ],
    },
    {
        "slug": "mid-autumn-office",
        "title": "Mid-Autumn, for people with an office",
        "kicker": "Culture",
        "category": "culture",
        "excerpt": "25 September 2026. Someone will give you a box of mooncakes. Here is what to do with it.",
        "updated": "14 September 2026",
        "readMinutes": 4,
        "hero": "/live/kampong-glam.jpg",
        "tags": ["mid-autumn", "mooncake", "festival", "office"],
        "body": [
            p("Mid-Autumn is lanterns and a pastry that is denser than it looks. In an office it is a round of gift boxes: lotus seed, salted egg yolk, the expensive hotel ones, the snow-skin ones from a bakery trying harder."),
            ul([
                "If you receive a box, say thank you and leave it in the pantry unless it has your name on it.",
                "If you give a box, one good one beats four mediocre ones. Do not make it a competition with the other manager.",
                "Take children to a lantern display once. Chinatown or the Chinese Garden. Buy them a paper lantern that will not survive the MRT.",
            ]),
            p("You do not need to understand the poetry. You need to not walk past the pantry box like it is strange. It is September in Singapore. Eat the cake."),
        ],
    },
    {
        "slug": "after-seven",
        "title": "After 7pm, where does the city go?",
        "kicker": "Night",
        "category": "city",
        "excerpt": "CBD empties. Heartlands cook. A few streets get loud. Knowing which is which is the difference between a night out and a deserted pavement.",
        "updated": "10 August 2026",
        "readMinutes": 5,
        "hero": "/live/marina-bay.jpg",
        "tags": ["nightlife", "cbd", "holland village", "tiong bahru", "keong saik"],
        "body": [
            p("Singapore does not have a 2am culture in most postcodes. It has pockets. Standing on a Monday in Raffles Place at 8.30pm wondering where the people went is a rite of passage."),
            ul([
                "Weeknight dinner: Tiong Bahru, Joo Chiat, Ann Siang, Keong Saik, Dempsey if someone else is paying.",
                "Drinks: Duxton, Club Street, Keong Saik, Boat Quay if you like that sort of thing, Tanjong Pagar for the offices that still go out.",
                "Holland Village is a habit, not a discovery. It still works.",
                "Late food: 24-hour kopitiams, prata, and the few hawker centres that run late (not as many as you were promised).",
            ]),
            p("If you want a city that walks at midnight, you will be disappointed. If you want a city that lets you be in bed at 10.30 and still have had a good evening, you are in the right place."),
        ],
    },
    {
        "slug": "the-helper",
        "title": "The helper, if you have one",
        "kicker": "Family",
        "category": "family",
        "excerpt": "A transfer maid is not a subscription. The law is specific. The relationship is the thing that will make or break your household.",
        "updated": "2 August 2026",
        "readMinutes": 7,
        "hero": "/live/playground.jpg",
        "tags": ["helper", "maid", "mom", "levy", "family"],
        "body": [
            p("Many expat households here employ a live-in migrant domestic worker. MOM has rules: rest days, levy, medical, insurance, no illegal deployment. Read them. Then behave like a decent employer on top of the rules."),
            ul([
                "A weekly rest day is not a favour. If she works it, pay the extra, in writing.",
                "Food, a bed that is a bed, and a door that closes.",
                "Her phone is hers. Her passport should not live in your safe “for safekeeping” unless she asked.",
                "You are not her parent. You are her boss, in her home, which is also yours. That is a strange arrangement. Stay strange in the direction of respect.",
            ]),
            callout("Budget: salary often S$850–1,200 plus levy (S$300 for many households, concessions exist), plus food and medical. The cheap helper is usually expensive in other ways.", "info"),
            p("If you do not want a helper, you can live here without one. Plenty of people do. Do not hire someone because the condo WhatsApp assumes you will."),
        ],
    },
]

events = {
    "updated": "14 September 2026",
    "lead": "What the island is doing. Not a tourist brochure — the weeks a resident actually plans around.",
    "items": [
        {
            "id": "mid-autumn-2026",
            "title": "Mid-Autumn Festival",
            "dates": "25 September 2026",
            "when": "2026-09-25",
            "venue": "Chinatown, Chinese Garden, every office pantry",
            "kind": "festival",
            "blurb": "Mooncakes, lanterns, a public-holiday-adjacent Friday. Eat the snow-skin. Take the kids out once.",
            "href": "/live/mid-autumn-office",
        },
        {
            "id": "f1-2026",
            "title": "Formula 1 Singapore Grand Prix",
            "dates": "9–11 October 2026",
            "when": "2026-10-09",
            "venue": "Marina Bay Street Circuit",
            "kind": "sport",
            "blurb": "First Sprint weekend here. The Killers Saturday, Lana Del Rey Sunday. Road closures 7–13 Oct. Last trains late from City Hall.",
            "href": "/live/f1-month-if-you-live-here",
            "featured": True,
        },
        {
            "id": "f1-closures",
            "title": "Marina Centre road closures",
            "dates": "7–13 October 2026",
            "when": "2026-10-07",
            "venue": "Marina Centre / Padang",
            "kind": "city",
            "blurb": "LTA: roads shut 12.01am 7 Oct, fully open 5.30am 13 Oct. Work from home. Do not drive to the bay.",
            "href": "/live/f1-month-if-you-live-here",
        },
        {
            "id": "deepavali-2026",
            "title": "Deepavali",
            "dates": "8 November 2026",
            "when": "2026-11-08",
            "venue": "Little India",
            "kind": "festival",
            "blurb": "The lights go up weeks before. Go in the evening. Eat. It is a public holiday.",
            "href": "/live/public-holidays-2026",
        },
        {
            "id": "parkrun",
            "title": "Parkrun (every Saturday)",
            "dates": "Saturdays, 7.30am",
            "when": "recurring",
            "venue": "East Coast, West Coast and others",
            "kind": "sport",
            "blurb": "Free 5 km. The most reliable way to see the same people every week without joining a club with a joining fee.",
            "href": "/live/sports-clubs-repeating-rooms",
        },
        {
            "id": "ubi-bumboat",
            "title": "Pulau Ubin weekends",
            "dates": "Every weekend",
            "when": "recurring",
            "venue": "Changi Point ferry",
            "kind": "weekend",
            "blurb": "Bumboats when full. Last boat back is not a suggestion. Bicycle at the jetty.",
            "href": "/live/weekend-that-isnt-orchard",
        },
        {
            "id": "esplanade-free",
            "title": "Esplanade free stages",
            "dates": "Most weekends",
            "when": "recurring",
            "venue": "Esplanade – Theatres on the Bay",
            "kind": "arts",
            "blurb": "Concourse and outdoor performances that are actually good. Aircon adjacent. Check the month’s grid.",
            "href": "/live/after-seven",
        },
        {
            "id": "night-festival-hangover",
            "title": "Museum late nights",
            "dates": "Check NMS / National Gallery",
            "when": "recurring",
            "venue": "Civic District",
            "kind": "arts",
            "blurb": "When the Civic District stays open after dinner. The cheapest date that still feels like the city.",
            "href": "/live/after-seven",
        },
    ],
}

ROOT.joinpath("live.json").write_text(json.dumps(stories, indent=2) + "\n")
ROOT.joinpath("events.json").write_text(json.dumps(events, indent=2) + "\n")
print("stories", len(stories), "events", len(events["items"]))
