/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as EventsRouteImport } from './routes/events'
import { Route as SearchRouteImport } from './routes/search'
import { Route as DirectoryIndexRouteImport } from './routes/directory.index'
import { Route as DirectoryCategoryRouteImport } from './routes/directory.$category'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as LiveIndexRouteImport } from './routes/live.index'
import { Route as LiveSlugRouteImport } from './routes/live.$slug'
import { Route as NeighbourhoodsIndexRouteImport } from './routes/neighbourhoods.index'
import { Route as NeighbourhoodsSlugRouteImport } from './routes/neighbourhoods.$slug'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsCompassRouteImport } from './routes/tools.compass'
import { Route as ToolsCostOfLivingRouteImport } from './routes/tools.cost-of-living'
import { Route as ToolsEpSalaryRouteImport } from './routes/tools.ep-salary'
import { Route as ToolsTaxRouteImport } from './routes/tools.tax'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryIndexRoute = DirectoryIndexRouteImport.update({
  id: '/directory/',
  path: '/directory/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryCategoryRoute = DirectoryCategoryRouteImport.update({
  id: '/directory/$category',
  path: '/directory/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveSlugRoute = LiveSlugRouteImport.update({
  id: '/live/$slug',
  path: '/live/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighbourhoodsIndexRoute = NeighbourhoodsIndexRouteImport.update({
  id: '/neighbourhoods/',
  path: '/neighbourhoods/',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighbourhoodsSlugRoute = NeighbourhoodsSlugRouteImport.update({
  id: '/neighbourhoods/$slug',
  path: '/neighbourhoods/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCompassRoute = ToolsCompassRouteImport.update({
  id: '/tools/compass',
  path: '/tools/compass',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCostOfLivingRoute = ToolsCostOfLivingRouteImport.update({
  id: '/tools/cost-of-living',
  path: '/tools/cost-of-living',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsEpSalaryRoute = ToolsEpSalaryRouteImport.update({
  id: '/tools/ep-salary',
  path: '/tools/ep-salary',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTaxRoute = ToolsTaxRouteImport.update({
  id: '/tools/tax',
  path: '/tools/tax',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/events': typeof EventsRoute
  '/search': typeof SearchRoute
  '/directory/$category': typeof DirectoryCategoryRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/live/$slug': typeof LiveSlugRoute
  '/neighbourhoods/$slug': typeof NeighbourhoodsSlugRoute
  '/tools/compass': typeof ToolsCompassRoute
  '/tools/cost-of-living': typeof ToolsCostOfLivingRoute
  '/tools/ep-salary': typeof ToolsEpSalaryRoute
  '/tools/tax': typeof ToolsTaxRoute
  '/directory/': typeof DirectoryIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/live/': typeof LiveIndexRoute
  '/neighbourhoods/': typeof NeighbourhoodsIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/events': typeof EventsRoute
  '/search': typeof SearchRoute
  '/directory/$category': typeof DirectoryCategoryRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/live/$slug': typeof LiveSlugRoute
  '/neighbourhoods/$slug': typeof NeighbourhoodsSlugRoute
  '/tools/compass': typeof ToolsCompassRoute
  '/tools/cost-of-living': typeof ToolsCostOfLivingRoute
  '/tools/ep-salary': typeof ToolsEpSalaryRoute
  '/tools/tax': typeof ToolsTaxRoute
  '/directory': typeof DirectoryIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/live': typeof LiveIndexRoute
  '/neighbourhoods': typeof NeighbourhoodsIndexRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/events': typeof EventsRoute
  '/search': typeof SearchRoute
  '/directory/$category': typeof DirectoryCategoryRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/live/$slug': typeof LiveSlugRoute
  '/neighbourhoods/$slug': typeof NeighbourhoodsSlugRoute
  '/tools/compass': typeof ToolsCompassRoute
  '/tools/cost-of-living': typeof ToolsCostOfLivingRoute
  '/tools/ep-salary': typeof ToolsEpSalaryRoute
  '/tools/tax': typeof ToolsTaxRoute
  '/directory/': typeof DirectoryIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/live/': typeof LiveIndexRoute
  '/neighbourhoods/': typeof NeighbourhoodsIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advertise'
    | '/events'
    | '/search'
    | '/directory/$category'
    | '/guides/$slug'
    | '/live/$slug'
    | '/neighbourhoods/$slug'
    | '/tools/compass'
    | '/tools/cost-of-living'
    | '/tools/ep-salary'
    | '/tools/tax'
    | '/directory/'
    | '/guides/'
    | '/live/'
    | '/neighbourhoods/'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advertise'
    | '/events'
    | '/search'
    | '/directory/$category'
    | '/guides/$slug'
    | '/live/$slug'
    | '/neighbourhoods/$slug'
    | '/tools/compass'
    | '/tools/cost-of-living'
    | '/tools/ep-salary'
    | '/tools/tax'
    | '/directory'
    | '/guides'
    | '/live'
    | '/neighbourhoods'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advertise'
    | '/events'
    | '/search'
    | '/directory/$category'
    | '/guides/$slug'
    | '/live/$slug'
    | '/neighbourhoods/$slug'
    | '/tools/compass'
    | '/tools/cost-of-living'
    | '/tools/ep-salary'
    | '/tools/tax'
    | '/directory/'
    | '/guides/'
    | '/live/'
    | '/neighbourhoods/'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvertiseRoute: typeof AdvertiseRoute
  EventsRoute: typeof EventsRoute
  SearchRoute: typeof SearchRoute
  DirectoryCategoryRoute: typeof DirectoryCategoryRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  LiveSlugRoute: typeof LiveSlugRoute
  NeighbourhoodsSlugRoute: typeof NeighbourhoodsSlugRoute
  ToolsCompassRoute: typeof ToolsCompassRoute
  ToolsCostOfLivingRoute: typeof ToolsCostOfLivingRoute
  ToolsEpSalaryRoute: typeof ToolsEpSalaryRoute
  ToolsTaxRoute: typeof ToolsTaxRoute
  DirectoryIndexRoute: typeof DirectoryIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  LiveIndexRoute: typeof LiveIndexRoute
  NeighbourhoodsIndexRoute: typeof NeighbourhoodsIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/': {
      id: '/directory/'
      path: '/directory'
      fullPath: '/directory/'
      preLoaderRoute: typeof DirectoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/$category': {
      id: '/directory/$category'
      path: '/directory/$category'
      fullPath: '/directory/$category'
      preLoaderRoute: typeof DirectoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/': {
      id: '/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$slug': {
      id: '/live/$slug'
      path: '/live/$slug'
      fullPath: '/live/$slug'
      preLoaderRoute: typeof LiveSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighbourhoods/': {
      id: '/neighbourhoods/'
      path: '/neighbourhoods'
      fullPath: '/neighbourhoods/'
      preLoaderRoute: typeof NeighbourhoodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighbourhoods/$slug': {
      id: '/neighbourhoods/$slug'
      path: '/neighbourhoods/$slug'
      fullPath: '/neighbourhoods/$slug'
      preLoaderRoute: typeof NeighbourhoodsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/compass': {
      id: '/tools/compass'
      path: '/tools/compass'
      fullPath: '/tools/compass'
      preLoaderRoute: typeof ToolsCompassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/cost-of-living': {
      id: '/tools/cost-of-living'
      path: '/tools/cost-of-living'
      fullPath: '/tools/cost-of-living'
      preLoaderRoute: typeof ToolsCostOfLivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ep-salary': {
      id: '/tools/ep-salary'
      path: '/tools/ep-salary'
      fullPath: '/tools/ep-salary'
      preLoaderRoute: typeof ToolsEpSalaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/tax': {
      id: '/tools/tax'
      path: '/tools/tax'
      fullPath: '/tools/tax'
      preLoaderRoute: typeof ToolsTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvertiseRoute: AdvertiseRoute,
  EventsRoute: EventsRoute,
  SearchRoute: SearchRoute,
  DirectoryCategoryRoute: DirectoryCategoryRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  LiveSlugRoute: LiveSlugRoute,
  NeighbourhoodsSlugRoute: NeighbourhoodsSlugRoute,
  ToolsCompassRoute: ToolsCompassRoute,
  ToolsCostOfLivingRoute: ToolsCostOfLivingRoute,
  ToolsEpSalaryRoute: ToolsEpSalaryRoute,
  ToolsTaxRoute: ToolsTaxRoute,
  DirectoryIndexRoute: DirectoryIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  LiveIndexRoute: LiveIndexRoute,
  NeighbourhoodsIndexRoute: NeighbourhoodsIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
